version: '3'
services:
  golang-api:
    build:
      context: ./golang
      dockerfile: Dockerfile.golang
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M

  nodejs-api:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M

  java-api:
    build:
      context: ./java/BenchmarkTcc
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M